name: Exercice 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Chrome and Firefox extension
        run: |
          npm run build
          npm run build:firefox
          npm run zip
          npm run zip:firefox

      - name: Upload artifact containing Chrome packages
        uses: actions/upload-artifact@v4
        with:
          name: ChromePackages
          path: .output/addon-background-color-0.0.1-chrome.zip

      - name: Upload artifact containing Firefox packages
        uses: actions/upload-artifact@v4
        with:
          name: FirefoxPackages
          path: |
            .output/addon-background-color-0.0.1-firefox.zip