name: Exercice 3 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout repository
      -uses: actions/checkout@v4

      -name: Install dependencies
      -run: npm install

      -name: Build Chrome and Firefox extension
      -run: |
        npm run build
        npm run build:firefox
        npm run zip     

